"""'write_new_phones'

Revision ID: 1bf14b091210
Revises: 79510674bbe7
Create Date: 2022-08-06 19:54:56.868756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf14b091210'
down_revision = '79510674bbe7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
