"""'reuse'

Revision ID: 4faf48f47606
Revises: 1bf14b091210
Create Date: 2022-08-06 20:00:14.478513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faf48f47606'
down_revision = '1bf14b091210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('con_phon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['phone'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('con_phon')
    # ### end Alembic commands ###
