"""'Init'

Revision ID: 79510674bbe7
Revises: 
Create Date: 2022-08-06 18:22:47.803971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79510674bbe7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=10), nullable=True),
    sa.Column('emailll', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('con_phon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact'], ['phones.id'], ),
    sa.ForeignKeyConstraint(['phone'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('con_phon')
    op.drop_table('phones')
    op.drop_table('contact')
    # ### end Alembic commands ###
