"""'last_version'

Revision ID: 935b7d7bbb11
Revises: 4faf48f47606
Create Date: 2022-08-06 20:07:29.170796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935b7d7bbb11'
down_revision = '4faf48f47606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('con_phon_contact_fkey', 'con_phon', type_='foreignkey')
    op.drop_constraint('con_phon_phone_fkey', 'con_phon', type_='foreignkey')
    op.create_foreign_key(None, 'con_phon', 'contact', ['contact'], ['id'])
    op.create_foreign_key(None, 'con_phon', 'phones', ['phone'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'con_phon', type_='foreignkey')
    op.drop_constraint(None, 'con_phon', type_='foreignkey')
    op.create_foreign_key('con_phon_phone_fkey', 'con_phon', 'contact', ['phone'], ['id'])
    op.create_foreign_key('con_phon_contact_fkey', 'con_phon', 'phones', ['contact'], ['id'])
    # ### end Alembic commands ###
